function BoiseGreenBikeTripData2015 = importboisetrip(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   BOISEGREENBIKETRIPDATA2015 = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   BOISEGREENBIKETRIPDATA2015 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   BoiseGreenBikeTripData2015 = importfile('Boise_GreenBike_Trip_Data_2015.csv', 2, 10130);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/12/05 02:55:04

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,9,11,15,16]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using the
% specified date format.
try
    dates{12} = datetime(dataArray{12}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{12} = cellfun(@(x) x(2:end-1), dataArray{12}, 'UniformOutput', false);
        dates{12} = datetime(dataArray{12}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
    catch
        dates{12} = repmat(datetime([NaN NaN NaN]), size(dataArray{12}));
    end
end

dates = dates(:,12);

%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,9,11,15,16]);
rawStringColumns = string(raw(:, [2,3,4,5,6,7,8,10,13,14]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [1,2,3,4,5,6,7,8,9,10]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
BoiseGreenBikeTripData2015 = table;
BoiseGreenBikeTripData2015.uniqueID = cell2mat(rawNumericColumns(:, 1));
BoiseGreenBikeTripData2015.paymentPlan = categorical(rawStringColumns(:, 1));
BoiseGreenBikeTripData2015.startHub = categorical(rawStringColumns(:, 2));
BoiseGreenBikeTripData2015.startDate = categorical(rawStringColumns(:, 3));
BoiseGreenBikeTripData2015.startTimeRange = categorical(rawStringColumns(:, 4));
BoiseGreenBikeTripData2015.endHub = categorical(rawStringColumns(:, 5));
BoiseGreenBikeTripData2015.endDate = categorical(rawStringColumns(:, 6));
BoiseGreenBikeTripData2015.endTimeRange = categorical(rawStringColumns(:, 7));
BoiseGreenBikeTripData2015.bikeID = cell2mat(rawNumericColumns(:, 2));
BoiseGreenBikeTripData2015.bikeName = categorical(rawStringColumns(:, 8));
BoiseGreenBikeTripData2015.distanceMiles = cell2mat(rawNumericColumns(:, 3));
BoiseGreenBikeTripData2015.duration = dates{:, 1};
BoiseGreenBikeTripData2015.rentalAccess = categorical(rawStringColumns(:, 9));
BoiseGreenBikeTripData2015.multipleRental = categorical(rawStringColumns(:, 10));
BoiseGreenBikeTripData2015.totalCost = cell2mat(rawNumericColumns(:, 4));
BoiseGreenBikeTripData2015.FID = cell2mat(rawNumericColumns(:, 5));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% BoiseGreenBikeTripData2015.duration=datenum(BoiseGreenBikeTripData2015.duration);

